import { db } from '../../models';
import {ProductAttributeValues} from '../../models/product-models/ProductAttributeValues';

export const ProductAttributeValuesSeeder = () => db.sequelize.Promise.map([
  { productId: 1, attributeValueId: 1 },
  { productId: 2, attributeValueId: 1 },
  { productId: 3, attributeValueId: 1 },
  { productId: 4, attributeValueId: 1 },
  { productId: 5, attributeValueId: 5 },
  { productId: 5, attributeValueId: 9 },
  { productId: 6, attributeValueId: 5 },
  { productId: 6, attributeValueId: 9 },
  { productId: 7, attributeValueId: 5 },
  { productId: 7, attributeValueId: 9 },
  { productId: 8, attributeValueId: 5 },
  { productId: 8, attributeValueId: 9 },
  { productId: 9, attributeValueId: 5 },
  { productId: 9, attributeValueId: 9 },
  { productId: 10, attributeValueId: 5 },
  { productId: 10, attributeValueId: 9 },
  { productId: 11, attributeValueId: 5 },
  { productId: 11, attributeValueId: 9 },
  { productId: 12, attributeValueId: 5 },
  { productId: 12, attributeValueId: 9 },
  { productId: 13, attributeValueId: 5 },
  { productId: 13, attributeValueId: 9 },
  { productId: 14, attributeValueId: 8 },
  { productId: 15, attributeValueId: 13 },
  { productId: 15, attributeValueId: 9 },
  { productId: 16, attributeValueId: 1 },
  { productId: 17, attributeValueId: 1 },
  { productId: 18, attributeValueId: 1 },
  { productId: 19, attributeValueId: 1 },
  { productId: 20, attributeValueId: 6 },
  { productId: 20, attributeValueId: 7 },
  { productId: 21, attributeValueId: 6 },
  { productId: 21, attributeValueId: 7 },
  { productId: 22, attributeValueId: 6 },
  { productId: 22, attributeValueId: 7 },
  { productId: 23, attributeValueId: 6 },
  { productId: 23, attributeValueId: 7 },
  { productId: 24, attributeValueId: 6 },
  { productId: 24, attributeValueId: 7 },
  { productId: 25, attributeValueId: 6 },
  { productId: 25, attributeValueId: 7 },
  { productId: 26, attributeValueId: 6 },
  { productId: 26, attributeValueId: 7 }
], category => ProductAttributeValues.create(category));
