import { db } from '../../models';
import {ProductSKU} from '../../models/product-models/ProductSKU';

export const ProductSKUSeeder = () => db.sequelize.Promise.map([
  { attributeValueId: 1, productId: 1, price: 14, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 1, productId: 2, price: 14, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 1, productId: 3, price: 14, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 1, productId: 4, price: 14, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 5, productId: 5, price: 7, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 9, productId: 5, price: 25, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 5, productId: 6, price: 7, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 9, productId: 6, price: 25, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 5, productId: 7, price: 7, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 9, productId: 7, price: 25, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 5, productId: 8, price: 7, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 9, productId: 8, price: 25, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 5, productId: 9, price: 7, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 9, productId: 9, price: 25, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 5, productId: 10, price: 7, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 9, productId: 10, price: 25, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 5, productId: 11, price: 7, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 9, productId: 11, price: 25, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 5, productId: 12, price: 7, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 9, productId: 12, price: 25, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 5, productId: 13, price: 7, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 9, productId: 13, price: 25, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 8, productId: 14, price: 25, quantity: 40, trackStock: true, isActive: true },
  { attributeValueId: 13, productId: 15, price: 30, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 9, productId: 15, price: 45, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 1, productId: 16, price: 4, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 1, productId: 17, price: 4, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 1, productId: 18, price: 4, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 1, productId: 19, price: 4, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 6, productId: 20, price: 8, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 7, productId: 20, price: 14, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 6, productId: 21, price: 8, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 7, productId: 21, price: 14, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 6, productId: 22, price: 9, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 7, productId: 22, price: 16, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 6, productId: 23, price: 22, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 7, productId: 23, price: 40, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 6, productId: 24, price: 8, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 7, productId: 24, price: 14, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 6, productId: 25, price: 8, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 7, productId: 25, price: 14, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 6, productId: 26, price: 8, quantity: 0, trackStock: false, isActive: true },
  { attributeValueId: 7, productId: 26, price: 14, quantity: 0, trackStock: false, isActive: true }
], sku => ProductSKU.create(sku));
